openapi: 3.0.3
info:
  title: "Haal Centraal BRK historie bevragen"
  version: "1.0.0-dev"
paths:
  /publiekrechtelijkebeperkinghistorischevoorkomens/{kadastraalonroerendezaakidentificatie}:
    $ref: "publiek-rechtelijke-beperkingen-historische-voorkomens.yaml#/paths/~1publiekrechtelijkebeperkinghistorischevoorkomens~1{kadastraalonroerendezaakidentificatie}"